name: Hosty
description: Automate your deployments with ease
inputs:
  server_ip:
    description: The IP address of the server
    required: true
  server_user:
    description: The username to use to connect to the server
    required: true
  ssh_private_key:
    description: The private ssh key to use to connect to the server
    required: true
  server_sudo_pass:
    description: The sudo password of the user on the server
    required: true
  handler:
    description: The Javascript file to run
    required: true
runs:
  using: composite
  steps:
  - name: Set up SSH
    uses: webfactory/ssh-agent@v0.9.0
    with:
      ssh-private-key: ${{ inputs.ssh_private_key }}
  - name: Add VPS to known_hosts
    run: ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
    shell: bash
  - name: Delete from server
    env:
      hosty_server_ip: ${{ inputs.server_ip }}
      hosty_server_user: ${{ inputs.server_user }}
      hosty_server_sudo_pass: ${{ inputs.server_sudo_pass }}
      hosty_repo: ${{ github.repository }}
      hosty_branch: ${{ github.event_name == 'delete' && github.event.ref || github.head_ref || github.ref_name }}
    run: node ${{ inputs.handler }}
    shell: bash
