name: Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          check-latest: true
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r build
      - run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
