name: Tests
on:
  push:
    branches: [main]
    paths-ignore: ['docs/**', '**/README.md']
  pull_request:
    paths-ignore: ['docs/**', '**/README.md']
jobs:
  get-hosty-test-files:
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.set-matrix.outputs.test-files }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "test-files=$(ls tests/*.test.ts | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test-hosty:
    needs: [get-hosty-test-files]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file: ${{fromJson(needs.get-hosty-test-files.outputs.test-files)}}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test ${{matrix.test-file}}