name: Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  functional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
      - run: npm test